project:
  type: website
  output-dir: docs

website:
  title: "Dallin Robinson - Data Science Portfolio"
  description: "A showcase of my data science projects and learning journey"

  navbar:
    background: primary
    left:
      - text: "Home"
        href: index.md
      - text: "About Me"
        href: about.md
      - text: "Blog"
        href: blog.qmd
    right:
      - icon: github
        href: https://github.com/dallinrobinson
      - icon: linkedin
        href: https://linkedin.com/in/dallin-robinson

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
